version: "3.9"

services:
  iris_app:
    build: .
    ports:
<<<<<<< HEAD
<<<<<<< HEAD
      - "8080:8080"
=======
      - "8080:8080"
      
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
      
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "8081:8081"
    depends_on:
      - mongo
>>>>>>> 69e5547c90f067ece325601f878c99b64debd886
=======
      - "8080:8080"
>>>>>>> 88400a463147748c7e8d504081fa7f0992181c29
